---
title: "Introduction to ggtt"
author: "Janne Huovari"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_width: 5
    fig_height: 3
    toc: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r init, message=FALSE}

library(ggptt)
library(dplyr)
library(tidyr)

pdat <- economics %>% 
  select(date, psavert, uempmed) %>% 
  gather(vars, values, -date)
  

```


`ggptt` will also load `ggplot2`.

# PTT colours

### PTT colours: `ptt_pal()`

```{r ptt_colours}
scales::show_col(ptt_pal(6))
```

### VNK: `vnk_pal()`

```{r vnk_colours}
scales::show_col(vnk_pal(4))
```

## PTT scales

`scale_colour_ptt()` and `scale_fill_ptt()`

```{r scale_colour}

p <- ggplot(pdat, aes(x = date, y = values, colour = vars)) + 
  geom_line()

p

p + scale_colour_ptt()

```

## PTT theme


```{r theme_ptt}

p + theme_ptt()

```

`set_ptt()` sets PTT theme and colours

```{r set_ptt}

set_ptt()
p

```

Also `theme_map()` for maps.

## "the"-theme elemets

```{r the}

p + the_legend_bot()

p + the_title_blank()

p + the_title_blank(c("x", "l"))

p + the_x45()
```

## scale formaters

```{r format}

p + scale_x_date(labels = no_century)

# Percents
pdat2 <- pdat %>% mutate(values = values/100)
p %+% pdat2 + scale_y_continuous(labels = percent_comma)

# comma
p %+% pdat2 + scale_y_continuous(labels = deci_comma)

```

